### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by jaybeeuu** [fakundo/preact-transitioning#14]
Great little library!

Any plans to add type definitions?

Would you accept a PR with some? I've built out a `.d.ts` so i could use this i n a ts project. I'd be happy to raise an PR if you would like them, otherwise i could add them to DefinitelyTyped?

**Comment by fakundo** [comment]
Hey! I'm actually planning to rewrite and refactor this project in TypeScript soon. I'm glad you liked it, so don't worry. Thank you.

**Comment by jaybeeuu** [comment]
:) Sounds great! Thanks! looking forward to it!
